const allCities = [
  // Iran Cities
  { label: 'tehran', country: 'iran' },
  { label: 'isfahan', country: 'iran' },
  { label: 'shiraz', country: 'iran' },
  { label: 'mashhad', country: 'iran' },
  { label: 'tabriz', country: 'iran' },
  { label: 'yazd', country: 'iran' },
  { label: 'ahvaz', country: 'iran' },
  { label: 'kish', country: 'iran' },
  { label: 'qom', country: 'iran' },
  { label: 'kerman', country: 'iran' },

  // World Cities
  { label: 'new york', country: 'usa' },
  { label: 'london', country: 'uk' },
  { label: 'paris', country: 'france' },
  { label: 'tokyo', country: 'japan' },
  { label: 'hong kong', country: 'china' },
  { label: 'singapore', country: 'singapore' },
  { label: 'dubai', country: 'uae' },
  { label: 'beijing', country: 'china' },
  { label: 'los angeles', country: 'usa' },
  { label: 'sydney', country: 'australia' },
  { label: 'chicago', country: 'usa' },
  { label: 'shanghai', country: 'china' },
  { label: 'toronto', country: 'canada' },
  { label: 'berlin', country: 'germany' },
  { label: 'madrid', country: 'spain' },
  { label: 'amsterdam', country: 'netherlands' },
  { label: 'seoul', country: 'south korea' },
  { label: 'san francisco', country: 'usa' },
  { label: 'rome', country: 'italy' },
  { label: 'moscow', country: 'russia' },
  { label: 'melbourne', country: 'australia' },
  { label: 'washington, d.c.', country: 'usa' },
  { label: 'barcelona', country: 'spain' },
  { label: 'vienna', country: 'austria' },
  { label: 'zurich', country: 'switzerland' },
  { label: 'brussels', country: 'belgium' },
  { label: 'milan', country: 'italy' },
  { label: 'boston', country: 'usa' },
  { label: 'osaka', country: 'japan' },
  { label: 'taipei', country: 'taiwan' },
  { label: 'stockholm', country: 'sweden' },
  { label: 'vancouver', country: 'canada' },
  { label: 'munich', country: 'germany' },
  { label: 'copenhagen', country: 'denmark' },
  { label: 'dublin', country: 'ireland' },
  { label: 'buenos aires', country: 'argentina' },
  { label: 'istanbul', country: 'turkey' },
  { label: 'frankfurt', country: 'germany' },
  { label: 'montreal', country: 'canada' },
  { label: 'miami', country: 'usa' },
  { label: 'bangkok', country: 'thailand' },
  { label: 'mexico city', country: 'mexico' },
  { label: 'sao paulo', country: 'brazil' },
  { label: 'prague', country: 'czech republic' },
  { label: 'mumbai', country: 'india' },
  { label: 'lisbon', country: 'portugal' },
  { label: 'helsinki', country: 'finland' },
  { label: 'oslo', country: 'norway' },
  { label: 'auckland', country: 'new zealand' },
  { label: 'athens', country: 'greece' },
  { label: 'delhi', country: 'india' },
  { label: 'kuala lumpur', country: 'malaysia' },
  { label: 'budapest', country: 'hungary' },
  { label: 'warsaw', country: 'poland' },
  { label: 'riyadh', country: 'saudi arabia' },
  { label: 'doha', country: 'qatar' },
  { label: 'seattle', country: 'usa' },
  { label: 'houston', country: 'usa' },
  { label: 'tel aviv', country: 'israel' },
  { label: 'abu dhabi', country: 'uae' },
  { label: 'geneva', country: 'switzerland' },
  { label: 'rio de janeiro', country: 'brazil' },
  { label: 'johannesburg', country: 'south africa' },
  { label: 'bogota', country: 'colombia' },
  { label: 'santiago', country: 'chile' },
  { label: 'jakarta', country: 'indonesia' },
  { label: 'manila', country: 'philippines' },
  { label: 'lima', country: 'peru' },
  { label: 'cairo', country: 'egypt' },
  { label: 'nairobi', country: 'kenya' },
  { label: 'dallas', country: 'usa' },
  { label: 'atlanta', country: 'usa' },
  { label: 'philadelphia', country: 'usa' },
  { label: 'luxembourg', country: 'luxembourg' },
  { label: 'hamburg', country: 'germany' },
  { label: 'calgary', country: 'canada' },
  { label: 'perth', country: 'australia' },
  { 'label': 'brisbane', 'country': 'australia' },
  { 'label': 'edinburgh', 'country': 'uk' },
  { 'label': 'manchester', 'country': 'uk' },
  { 'label': 'kuwait city', 'country': 'kuwait' },
  { 'label': 'muscat', 'country': 'oman' },
  { 'label': 'casablanca', 'country': 'morocco' },
  { 'label': 'ho chi minh city', 'country': 'vietnam' },
  { 'label': 'kyiv', 'country': 'ukraine' },
  { 'label': 'bucharest', 'country': 'romania' },
  { 'label': 'beirut', 'country': 'lebanon' },
  { 'label': 'caracas', 'country': 'venezuela' },
  { 'label': 'panama city', 'country': 'panama' },
  { 'label': 'belgrade', 'country': 'serbia' },
  { 'label': 'sofia', 'country': 'bulgaria' },
  { 'label': 'zagreb', 'country': 'croatia' },
  { 'label': 'bratislava', 'country': 'slovakia' },
  { 'label': 'ljubljana', 'country': 'slovenia' },
  { 'label': 'riga', 'country': 'latvia' },
  { 'label': 'tallinn', 'country': 'estonia' },
  { 'label': 'vilnius', 'country': 'lithuania' },
];

export default allCities;